"""Level edge (design D4) — the luminance-dependent confirmed gamut edge (engine/level_gamut.py) and its wiring.

On a FALD / LC panel a dim primary is less saturated than the full-drive one (the LED pedestal leaks through the
closed cells): XYZ(pure k at code m) = own_k(m) + c·PQ(m)^γ·K. The edge is fitted from the raw pure-channel ramps,
persisted in mhc_params["level_edge"], and — only with the profile switch on, the vertex policy, the projection
solve, its deterministic gates passed and no falsification — replaces the full-drive triangle for the build and
verify targets. These pin the contract on synthetic panels generated BY the law (the suite never reads runs/):
the dict path stays bit-identical to the pre-D4 code, the fit recovers a known law, the map lands a Rec.2020
primary on the measured vertex at its luminance, the gates turn the feature off with a reason, the memo rules keep
legacy runs legacy, and a stage-CLI score equals the live verify.
"""
from __future__ import annotations

import hashlib
import json
from argparse import Namespace
from dataclasses import replace
from pathlib import Path

import numpy as np
import pytest

from dlc import metrics as M
from dlc.colormath import rgb_to_xyz_matrix
from dlc.engine import cube_quality as CQ
from dlc.engine import level_gamut as LG
from dlc.engine import lut_rbf
from dlc.engine.lut_rbf import build_cube, project_to_top
from dlc.engine.model import (DisplayErrorModel, Target, TargetSpace, _xy_to_uv, _xyz_to_uv, de_itp, score_hdr)

D65 = (0.3127, 0.3290)
TARGET = Target.hdr_rec2020_pq(white_xy=D65)
RAW = TargetSpace(TARGET)
# The synthetic panel: constant OWN chromaticity per channel, own luminance ∝ PQ(code), plus the pedestal law.
OWN = {"R": (0.70, 0.30), "G": (0.18, 0.76), "B": (0.150, 0.060)}
GAIN = (0.28, 0.62, 0.08)
LAW = {"c": 0.05, "gamma": 0.5, "K": (0.26, 0.30)}
CODES = np.linspace(0.16, 0.82, 24)


def _xyY(x, y, Y=1.0):
    return np.array([x * Y / y, Y, (1.0 - x - y) * Y / y])


def law_xyz(levels, *, c=LAW["c"], gamma=LAW["gamma"], K=LAW["K"]):
    """XYZ of native drives (N, 3) on the synthetic panel: own light of each channel + ONE pedestal from the
    largest code (the two-channel composition law)."""
    levels = np.atleast_2d(np.asarray(levels, float))
    out = np.zeros((len(levels), 3))
    for k, ch in enumerate("RGB"):
        out += (GAIN[k] * LG._pq(levels[:, k]))[:, None] * _xyY(*OWN[ch])[None, :] * (levels[:, k:k + 1] > 0)
    mx = levels.max(axis=1)
    out += (c * LG._pq(mx) ** gamma * (mx > 0))[:, None] * _xyY(*K)[None, :]
    return out


def ramps(codes=CODES, **law):
    rgb = np.vstack([np.outer(codes, e) for e in np.eye(3)])
    xyz = law_xyz(rgb, **law)
    n = len(codes)
    return rgb, xyz, [xyz[(k + 1) * n - 1] for k in range(3)]


def fit(codes=CODES, wrgb=False, **law):
    rgb, xyz, peaks = ramps(codes, **law)
    return LG.fit_level_edge(rgb, xyz, channel_peak_xyz=peaks, white_xy=D65, floor_nits=0.1,
                             wrgb_nonadditive=wrgb)


def lattice(n=17, top=1.0):
    ax = np.linspace(0.0, top, n)
    B, G, R = np.meshgrid(ax, ax, ax, indexing="ij")
    return np.stack([R.ravel(), G.ravel(), B.ravel()], axis=1)


@pytest.fixture(scope="module")
def law_block():
    return fit()


@pytest.fixture(scope="module")
def law_gamut(law_block):
    return LG.LevelGamut.from_params(law_block)


@pytest.fixture(scope="module")
def additive_block():
    return fit(c=0.0)


# ---------------------------------------------------------------------------
# The dict path (every run before D4, and every run with the edge off) is untouched
# ---------------------------------------------------------------------------

PA32 = {"R": [0.6928, 0.3027], "G": [0.1829, 0.7498], "B": [0.1521, 0.0648]}


def _h(a) -> str:
    return hashlib.sha256(np.ascontiguousarray(a, dtype=np.float64).tobytes()).hexdigest()[:16]


def test_dict_path_is_bit_identical_to_the_pre_level_edge_code():
    # Hashes computed with the pre-D4 engine (main 086b344) on the same inputs: ideal targets under both OOG
    # policies, the HDR score (dE + clamp mask) and direct / projection cubes on a synthetic sub-gamut panel.
    g = lattice(17)
    sp = TargetSpace(TARGET, reachable_primaries=PA32)
    assert _h(sp.ideal_xyz(g)) == "cbf294b42e759fb8"
    chroma = TargetSpace(Target.hdr_rec2020_pq(white_xy=D65, oog_mapping="chroma-clip"), reachable_primaries=PA32)
    assert _h(chroma.ideal_xyz(g[::7])) == "c6137a17def60b7f"
    rng = np.random.default_rng(1)
    meas = sp.ideal_xyz(g) * (1 + 0.02 * rng.standard_normal(g.shape))
    r = score_hdr(g, meas, white_xy=D65, reachable_primaries=PA32)
    assert (_h(r["de_itp"]), _h(r["gamut_clamped"].astype(float))) == ("54b55a19062966c4", "2cf4f0cb73cb1ebf")
    nat = np.array(rgb_to_xyz_matrix(*PA32["R"], *PA32["G"], *PA32["B"], *D65))
    inv = np.linalg.inv(nat)

    def panel(s):
        xyz = RAW.ideal_xyz(np.asarray(s, float))
        return (np.clip((xyz / 1e4) @ inv.T, 0.0, 0.1) * np.array([1.02, 0.99, 1.0]) @ nat.T) * 1e4
    s = np.vstack([np.repeat(np.linspace(0.05, 0.75, 12)[:, None], 3, 1), rng.uniform(0, 0.75, (300, 3))])
    m = DisplayErrorModel(s, panel(s), TARGET, reachable_primaries=PA32, smoothing=1e-3)
    for mode, want in (("direct", "51f7100b585f4116"), ("projection", "7e7113cb3e1762fc")):
        cube = build_cube(m, 9, s, oog_solve=mode, max_correction=0.25, hold_above=0.75, best_iterate=True)
        assert _h(cube) == want, mode


# ---------------------------------------------------------------------------
# Fit + gates
# ---------------------------------------------------------------------------

def test_fit_recovers_a_known_pedestal_law(law_block):
    b = law_block
    assert b["status"] == "ok" and b["reason"] is None
    ped = b["pedestal"]
    assert ped["identifiable"] is True
    assert abs(ped["c"] - LAW["c"]) < 1e-4 and abs(ped["gamma"] - LAW["gamma"]) < 1e-3
    assert np.allclose(ped["K_xy"], LAW["K"], atol=1e-4)
    assert all(v.get("ok") for v in b["gates"].values())
    _, _, peaks = ramps()
    want = LG._xy(np.array(peaks))
    assert b["full_primaries"] == {ch: [round(float(p[0]), 6), round(float(p[1]), 6)] for ch, p in zip("RGB", want)}
    assert b["key"].startswith("sha256:") and b["summary"]["levels"] > 200


def test_an_additive_panel_fits_as_c_zero_and_equals_the_full_drive_vertex_map(additive_block):
    # No pedestal to see (OLED / local dimming off): additive composition, c = 0 — and then the level map IS today's
    # vertex map (straight edges, white-balanced anchors), bar the membership-tolerance band and the 1e-6 rounding
    # of the persisted reads (1e-4 dE here).
    b = additive_block
    assert b["status"] == "ok" and b["pedestal"]["identifiable"] is False and b["pedestal"]["c"] == 0.0
    g = LG.LevelGamut.from_params(b)
    lvl, vtx = TargetSpace(TARGET, reachable_primaries=g), TargetSpace(TARGET, reachable_primaries=g.full_primaries)
    grid = lattice(17)
    raw, a, v = RAW.ideal_xyz(grid), lvl.ideal_xyz(grid), vtx.ideal_xyz(grid)
    cl_l = lvl.level_clamped(raw)
    cl_v = np.any(np.abs(v - raw) > 1e-9 + 1e-6 * np.abs(raw).sum(1)[:, None], axis=1)
    import colour
    over = colour.XYZ_to_RGB(raw / 1e4, vtx._reachable).max(axis=1) > 1 + 1e-4       # container clip (≈10000 nit)
    same = (cl_l == cl_v) & ~over
    d = de_itp(RAW.xyz_to_ictcp(a) - RAW.xyz_to_ictcp(v))
    assert same.sum() > 0.99 * (~over).sum() and d[same].max() < 1e-3
    r, r_e, _ = LG.outside_distance(g, raw[(cl_l != cl_v) & ~over])
    assert np.all(np.abs(r / r_e - 1.0) < 1e-4)                                          # only the tolerance band


def test_gates_turn_the_edge_off_with_a_reason():
    few = fit(codes=np.linspace(0.3, 0.8, 7))
    assert few["status"] == "rejected" and "too few" in few["reason"]
    wrgb = fit(wrgb=True)
    assert wrgb["status"] == "rejected" and "WRGB" in wrgb["reason"]
    unknown = fit(wrgb=None)                                 # the MHC build's WRGB verdict unavailable: not "additive"
    assert unknown["status"] == "rejected" and "unavailable" in unknown["reason"]
    steep = fit(gamma=1.5)                                   # a pedestal growing faster than the light: no law fit
    assert steep["status"] == "rejected" and "bound" in steep["reason"]
    kout = fit(K=(0.6, 0.6))                                 # pedestal chromaticity outside the native triangle
    assert kout["status"] == "rejected" and "not strictly inside" in kout["reason"]
    rgb, xyz, peaks = ramps()                                # two dim blue dropouts far below the pedestal
    xyz = xyz.copy()
    xyz[2 * len(CODES):2 * len(CODES) + 2] *= 0.02
    drop = LG.fit_level_edge(rgb, xyz, channel_peak_xyz=peaks, white_xy=D65, floor_nits=0.001)
    assert drop["status"] == "rejected" and "pedestal exceeds" in drop["reason"]
    for b in (few, wrgb, unknown, steep, kout, drop):
        gamut, rec = M.run_level_edge({}, {"level_edge": b}, switch="auto", oog_solve="projection")
        assert gamut is None and rec["enabled"] is False and "rejected" in rec["reason"]
        with pytest.raises(ValueError):
            LG.LevelGamut.from_params(b)
    missing = LG.fit_level_edge(np.zeros((3, 3)), np.zeros((3, 3)), channel_peak_xyz=None, white_xy=D65,
                                floor_nits=None)
    assert missing["status"] == "unavailable" and missing["reason"]


def test_multistart_keeps_the_interior_minimum_over_a_bound_local_minimum(monkeypatch):
    # A bad start stalls on a bound (γ = 1, rms ~0.015 on the PA32UCXR); the deterministic multi-start keeps the
    # lowest cost, so the edge is not rejected for a start that happened to fail.
    import scipy.optimize as so
    real = so.least_squares
    seen = []

    def fake(fun, x0, args=(), bounds=None, **kw):
        seen.append(x0[3])
        r = real(fun, x0, args=args, bounds=bounds, **kw)
        if x0[3] == 0.25:                                    # this start "stalls" on the gamma bound
            r.x = np.array([x0[0], x0[1], 0.2, 1.0])
            r.fun = fun(r.x, *args)
            r.cost = 0.5 * float(np.sum(r.fun ** 2))
            r.active_mask = np.array([0, 0, 0, 1])
        return r
    monkeypatch.setattr(so, "least_squares", fake)
    b = fit()
    assert sorted(seen) == [0.25, 0.5, 0.75]
    assert b["status"] == "ok" and abs(b["pedestal"]["gamma"] - LAW["gamma"]) < 1e-3


def test_key_is_stable_and_a_tampered_block_is_refused(law_block):
    again = fit()
    assert again["key"] == law_block["key"]
    rt = json.loads(json.dumps(law_block))                  # the run-record round trip
    assert LG.LevelGamut.from_params(rt).key() == law_block["key"]
    bad = json.loads(json.dumps(law_block))
    bad["ramps"]["B"]["xyz"][3][1] *= 1.01
    with pytest.raises(ValueError, match="key"):
        LG.LevelGamut.from_params(bad)
    # a pinned run whose record was edited: no crash — treated as a key mismatch (the orchestrator's seam) / unusable
    memo = {"enabled": True, "key": law_block["key"], "reason": None, "falsification": None}
    g, rec = M.run_level_edge({"oog_level_edge": memo}, {"level_edge": bad})
    assert g is None and rec["key_mismatch"] is True
    g, note = M.stage_level_gamut({"oog_level_edge": memo}, {"level_edge": bad})
    assert g is None and "unusable" in note


# ---------------------------------------------------------------------------
# The level polygon + map
# ---------------------------------------------------------------------------

def test_polygon_is_star_shaped_and_within_half_a_jnd_of_the_dense_physical_edge(law_gamut):
    g = law_gamut
    geo = g.geometry_gates()
    assert geo["star_shaped"]["ok"] and geo["anchor_order"]["ok"]
    W = _xy_to_uv(np.array(D65))[0]
    phi = np.linspace(0.0, np.pi / 2, 1025)
    ui, uj = g._code_dirs(phi)
    for Y in (0.2, 1.0, 10.0, 100.0, 600.0):
        for i, j in LG._PAIRS:
            s = g._solve_scale(i, j, np.full(len(phi), Y), ui, uj)
            X = g._xyz_at(i, j, s, ui, uj)
            X = X / X[:, 1:2] * Y
            uv = _xyz_to_uv(X)
            d = uv - W
            r = np.hypot(d[:, 0], d[:, 1])
            dirs = d / r[:, None]
            r_e = LG.ray_exit_poly(W, dirs, g.boundary_uv(np.full(len(X), Y)))
            poly = LG._uv_to_xyz(W + dirs * r_e[:, None], np.full(len(X), Y))
            de = de_itp(TargetSpace.xyz_to_ictcp(X) - TargetSpace.xyz_to_ictcp(poly))
            assert de.max() <= 0.5, (Y, i, j, de.max())


def test_level_map_keeps_in_gamut_rows_bit_identical_and_is_idempotent_and_luminance_preserving(law_gamut):
    sp = TargetSpace(TARGET, reachable_primaries=law_gamut)
    g = lattice(17, top=0.85)
    raw, out = RAW.ideal_xyz(g), sp.ideal_xyz(g)
    cl = sp.level_clamped(raw)
    assert 0 < cl.sum() < len(g)
    assert np.array_equal(out[~cl], raw[~cl])               # below 0.85 signal nothing hits the container clip
    assert np.array_equal(out[cl, 1], raw[cl, 1])           # CIE Y preserved exactly
    again = sp.ideal_xyz(sp.xyz_to_signal(out))
    lit = out[:, 1] > 0.01
    assert de_itp(RAW.xyz_to_ictcp(again[lit]) - RAW.xyz_to_ictcp(out[lit])).max() < 1e-6
    assert not np.any(sp.level_clamped(out[lit]))           # every landing point is on/inside the edge


def test_a_rec2020_primary_lands_on_the_measured_vertex_at_its_luminance(law_gamut):
    sp = TargetSpace(TARGET, reachable_primaries=law_gamut)
    for k in range(3):
        sig = np.zeros((6, 3))
        sig[:, k] = np.linspace(0.3, 0.8, 6)
        out = sp.ideal_xyz(sig)
        got = LG._xy(out)
        want = law_gamut.primaries_xy(out[:, 1])[:, k]
        assert np.abs(got - want).max() < 1e-9, k


def test_vertices_are_the_full_drive_primaries_above_the_top_read_and_the_floor_level_holds_below(law_gamut,
                                                                                                    law_block):
    g = law_gamut
    step = 10.0 ** (1.0 / LG.LEVELS_PER_DECADE)          # from the first level at/above the top read: held exactly
    for k, ch in enumerate("RGB"):
        ytop = law_block["ramps"][ch]["xyz"][-1][1]
        full = np.array(g.full_primaries[ch])
        for Y in (ytop * step * 1.0001, g.y_max * 3.0):
            assert np.abs(g.primaries_xy(np.array([Y]))[0, k] - full).max() < 1e-6
        assert np.abs(g.primaries_xy(np.array([ytop * 1.01]))[0, k] - full).max() < 1e-5   # within that level step
    assert np.array_equal(g.boundary_uv(np.array([0.01, 0.05])), g.boundary_uv(np.array([0.1, 0.1])))
    lo = g.primaries_xy(np.array([0.1]))[0]
    assert np.all(np.abs(lo - np.array([g.full_primaries[c] for c in "RGB"])).max(axis=1) > 0.01)   # dim = less saturated


def test_pushing_a_clamped_colour_further_out_never_unclamps(law_gamut):
    sp = TargetSpace(TARGET, reachable_primaries=law_gamut)
    raw = RAW.ideal_xyz(lattice(9, top=0.8))
    cl = sp.level_clamped(raw)
    W = _xy_to_uv(np.array(D65))[0]
    uv = _xyz_to_uv(raw[cl])
    for f in (1.02, 1.2):
        pushed = LG._uv_to_xyz(W + (uv - W) * f, raw[cl, 1])
        assert np.all(sp.level_clamped(pushed))


def test_target_space_level_path_needs_the_vertex_policy_and_the_target_white(law_gamut):
    with pytest.raises(ValueError, match="vertex"):
        TargetSpace(Target.hdr_rec2020_pq(white_xy=D65, oog_mapping="chroma-clip"), reachable_primaries=law_gamut)
    with pytest.raises(ValueError, match="white"):
        TargetSpace(Target.hdr_rec2020_pq(white_xy=(0.3000, 0.3300)), reachable_primaries=law_gamut)
    with pytest.raises(ValueError):
        TargetSpace(TARGET, reachable_primaries=PA32).level_clamped(np.ones((1, 3)))


def test_score_hdr_calls_a_patch_clamped_when_its_raw_target_is_outside_the_edge_at_its_luminance(law_gamut):
    sig = lattice(9, top=0.8)
    res = score_hdr(sig, RAW.ideal_xyz(sig), white_xy=D65, reachable_primaries=law_gamut)
    sp = TargetSpace(TARGET, reachable_primaries=law_gamut)
    assert np.array_equal(res["gamut_clamped"], sp.level_clamped(RAW.ideal_xyz(sig)))
    assert np.array_equal(res["ideal_xyz"], sp.ideal_xyz(sig))
    # a dim saturated blue inside the full-drive triangle (2 % toward white from the full-drive vertex, 1 nit) is
    # beyond the confirmed edge at its luminance: the full-drive target calls it reachable, the level edge clamps it
    W = _xy_to_uv(np.array(D65))[0]
    uv = W + 0.98 * (_xy_to_uv(np.array(law_gamut.full_primaries["B"])) - W)
    dim_blue = RAW.xyz_to_signal(LG._uv_to_xyz(uv, np.array([1.0])))
    assert not score_hdr(dim_blue, RAW.ideal_xyz(dim_blue), white_xy=D65,
                         reachable_primaries=law_gamut.full_primaries)["gamut_clamped"][0]
    assert score_hdr(dim_blue, RAW.ideal_xyz(dim_blue), white_xy=D65,
                     reachable_primaries=law_gamut)["gamut_clamped"][0]


# ---------------------------------------------------------------------------
# Falsification + cube diagnostics + the build re-map
# ---------------------------------------------------------------------------

def _mixed_drives(n=60, seed=4):
    rng = np.random.default_rng(seed)
    two = []
    for i, j in LG._PAIRS:
        d = np.zeros((n, 3))
        d[:, i] = rng.uniform(0.2, 0.8, n)
        d[:, j] = d[:, i] * rng.uniform(0.0, 1.0, n)
        two.append(d)
    return np.vstack([np.vstack([np.outer(CODES, e) for e in np.eye(3)])] + two)


def test_falsification_passes_on_the_panel_that_made_the_edge_and_trips_on_another(law_gamut):
    drives = _mixed_drives()
    own = CQ.level_edge_falsification(law_gamut, drives, law_xyz(drives), floor_nits=0.1)
    assert own["passed"] is True and own["n"] > 100 and own["max_de"] < 0.5
    other = CQ.level_edge_falsification(law_gamut, drives, law_xyz(drives, c=0.0), floor_nits=0.1)
    assert other["passed"] is False and other["over_jnd"] > 0 and other["worst"]["de_itp"] > 1.0
    none = CQ.level_edge_falsification(law_gamut, drives[:3], np.zeros((3, 3)), floor_nits=0.1)
    assert none["passed"] is None and none["n"] == 0


def _colorimetric_model(gamut, n=300, seed=0):
    """A panel that decodes Rec.2020 colorimetrically and clips at its native full-drive gamut, as a trained model
    whose target space carries the level edge."""
    prim = gamut.full_primaries
    nat = np.array(rgb_to_xyz_matrix(*prim["R"], *prim["G"], *prim["B"], *D65))
    inv = np.linalg.inv(nat)

    def panel(s):
        xyz = RAW.ideal_xyz(np.asarray(s, float))
        return (np.clip((xyz / 1e4) @ inv.T, 0.0, 0.1) @ nat.T) * 1e4
    rng = np.random.default_rng(seed)
    s = np.vstack([np.repeat(np.linspace(0.05, 0.75, 12)[:, None], 3, 1), rng.uniform(0.0, 0.75, (n, 3))])
    return DisplayErrorModel(s, panel(s), TARGET, reachable_primaries=gamut, smoothing=1e-3), s, panel


def test_cube_quality_splits_by_the_level_clamp_mask_and_reports_the_dim_ramps(law_gamut):
    m, s, panel = _colorimetric_model(law_gamut)
    sp = m.space
    assert sp.level_gamut is law_gamut
    pts = CQ.sample_points(0.6, 900)
    _, inv = CQ._native_matrices(law_gamut, D65)             # a gamut -> its full-drive triangle
    lvl_mask, _ = CQ._oog_mask(sp, RAW, inv, pts)
    full_mask, _ = CQ._is_oog(RAW, inv, pts)
    assert np.array_equal(lvl_mask, sp.level_clamped(RAW.ideal_xyz(pts)))
    assert np.any(lvl_mask != full_mask)
    ideal = CQ.ideal_cube(sp, 9, 0.6)
    q = CQ.cube_quality(m, ideal, sp, law_gamut, D65, hold_above=0.6, top=0.6)
    assert q["noise_gain"]["flag"] is False and abs(q["noise_gain"]["oog"]["p99"]) < 1e-9
    dim = q["ramp_excess"]["dim"]
    assert set(dim) == {"max", "ramp"} and abs(dim["max"]) < 1e-9
    prem = CQ.premise_check(s, panel(s), TARGET, law_gamut, D65, 1000.0)
    assert prem["passed"] is True


def test_projection_remaps_guard_nodes_onto_the_edge_after_the_top_projection(law_gamut, monkeypatch):
    m, s, _ = _colorimetric_model(law_gamut)
    top = 0.6
    captured = {}
    real = lut_rbf._solve_at

    def spy(model, solve, signal_points, **kw):
        captured["solve"] = solve.copy()
        return real(model, solve, signal_points, **kw)
    monkeypatch.setattr(lut_rbf, "_solve_at", spy)
    build_cube(m, 9, s, oog_solve="projection", max_correction=0.25, hold_above=top, best_iterate=True)
    solve = captured["solve"]
    sp = m.space
    assert not np.any(sp.level_clamped(RAW.ideal_xyz(solve)))       # no guard node aims outside the edge
    # ...which the top projection alone would not guarantee (the edge narrows as the projection dims a colour):
    g = lattice(9)
    level = lut_rbf.hold_lattice_level(top, 9)
    held = g[g.max(axis=1) > level + 1e-9]
    p = np.clip(sp.xyz_to_signal(sp.ideal_xyz(held)), 0.0, 1.0)
    over = p.max(axis=1) > level + 1e-9
    assert np.any(sp.level_clamped(RAW.ideal_xyz(project_to_top(p[over], level))))


# ---------------------------------------------------------------------------
# Memo rules (metrics.run_level_edge / stage_level_gamut)
# ---------------------------------------------------------------------------

def _passing(g):
    return {"passed": True, "n": 10}


def test_run_level_edge_enables_only_when_every_condition_holds(law_block):
    mp = {"level_edge": law_block}
    kw = dict(switch="auto", oog_mapping="vertex", oog_solve="projection", falsify=_passing)
    gamut, rec = M.run_level_edge({}, mp, **kw)
    assert gamut is not None and rec["enabled"] is True and rec["key"] == law_block["key"]
    assert rec["falsification"] == {"passed": True, "n": 10}
    for change, word in (({"oog_solve": "direct"}, "oog_solve"), ({"switch": "off"}, "profile"),
                         ({"oog_mapping": "chroma-clip"}, "oog_mapping"), ({"is_hdr": False}, "SDR")):
        g2, r2 = M.run_level_edge({}, mp, **{**kw, **change})
        assert g2 is None and r2["enabled"] is False and word in r2["reason"], change
    g3, r3 = M.run_level_edge({}, {}, **kw)
    assert g3 is None and "no level-edge block" in r3["reason"]
    # falsified (or undecidable) -> the gamut comes back for the seam, NOT enabled
    g4, r4 = M.run_level_edge({}, mp, **{**kw, "falsify": lambda g: {"passed": False}})
    assert g4 is not None and r4["enabled"] is False and r4["falsified"] is True
    g5, r5 = M.run_level_edge({}, mp, **{**kw, "falsify": lambda g: {"passed": None}})
    assert r5["falsified"] is True and "could not decide" in r5["reason"]


def test_run_level_edge_keeps_legacy_records_off_and_honours_a_pinned_memo(law_block):
    mp = {"level_edge": law_block}
    kw = dict(switch="auto", oog_mapping="vertex", oog_solve="projection", falsify=_passing)
    for stage in ("build-install-3dlut", "measure:verify", "verify"):
        g, rec = M.run_level_edge({"stages": {stage: {"status": "done"}}}, mp, **kw)
        assert g is None and "legacy" in rec["reason"]
    # an ABORTED build attempt (e.g. at a seam, before the memo was pinned) is not a built cube
    g, rec = M.run_level_edge({"stages": {"build-install-3dlut": {"status": "aborted"}}}, mp, **kw)
    assert g is not None and rec["enabled"] is True
    # an edge anchored on another white is refused fresh and reported as a mismatch when pinned
    g, rec = M.run_level_edge({}, mp, **kw, white_xy=(0.3000, 0.3300))
    assert g is None and "anchored on white" in rec["reason"]
    memo = {"enabled": True, "key": law_block["key"], "reason": None, "falsification": None}
    g, rec = M.run_level_edge({"oog_level_edge": memo, "stages": {"verify": {}}}, mp)
    assert g is not None and g.key() == law_block["key"]
    g, rec = M.run_level_edge({"oog_level_edge": {**memo, "key": "sha256:old"}}, mp)
    assert g is None and rec["key_mismatch"] is True and rec["current_key"] == law_block["key"]
    g, rec = M.run_level_edge({"oog_level_edge": memo}, mp, white_xy=(0.3000, 0.3300))
    assert g is None and rec["white_mismatch"] is True
    g, rec = M.run_level_edge({"oog_level_edge": {**memo, "enabled": False}}, mp, **kw)
    assert g is None and rec["enabled"] is False
    # stage CLIs: run memo by default, explicit off / on
    calib = {"oog_level_edge": memo}
    assert M.stage_level_gamut(calib, mp)[0] is not None
    assert M.stage_level_gamut({}, mp)[0] is None                    # no memo: legacy / never enabled
    assert M.stage_level_gamut(calib, mp, mode="off")[0] is None
    assert M.stage_level_gamut({}, mp, mode="on")[0] is not None
    assert M.stage_level_gamut({}, mp, mode="on", oog_mapping="chroma-clip")[0] is None
    g, note = M.stage_level_gamut(calib, mp, white_xy=(0.3000, 0.3300))    # an explicit other scoring white
    assert g is None and "anchored on white" in note
    with pytest.raises(ValueError):
        M.stage_level_gamut(calib, mp, mode="maybe")


def test_profile_level_edge_switch_defaults_off_and_validates():
    from dlc import calibration_profile as cp
    pq = {"transfer": {"type": "pq"}}
    assert cp._target_spec("rec2020_pq", pq).level_edge == "off"
    assert cp._target_spec("rec2020_pq", {**pq, "level_edge": "Auto"}).level_edge == "auto"
    assert cp._target_spec("rec2020_pq", {**pq, "level_edge": False}).level_edge == "off"   # YAML 1.1 bare `off`
    for bad in (True, "on", "force"):                                                        # YAML bare `on` too
        with pytest.raises(ValueError, match="level_edge"):
            cp._target_spec("rec2020_pq", {**pq, "level_edge": bad})
    assert cp.Profile.synthetic().targets["rec2020_pq"].level_edge == "off"


# ---------------------------------------------------------------------------
# Orchestration: build decision + seams, verify evidence, stage CLI == live verify, the level_edge CLI
# ---------------------------------------------------------------------------

def _write_ti3(path: Path, rgb, xyz):
    rows = [" ".join([f"{c * 100:.6f}" for c in r] + [f"{v:.6f}" for v in x]) for r, x in zip(rgb, xyz)]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("CTI3\n\nBEGIN_DATA_FORMAT\nRGB_R RGB_G RGB_B XYZ_X XYZ_Y XYZ_Z\nEND_DATA_FORMAT\n"
                    f"NUMBER_OF_SETS {len(rows)}\nBEGIN_DATA\n" + "\n".join(rows) + "\nEND_DATA\n",
                    encoding="utf-8")
    return path


def _mhc_params(block):
    p = block["full_primaries"]
    return {"primaries": {"rx": p["R"][0], "ry": p["R"][1], "gx": p["G"][0], "gy": p["G"][1],
                          "bx": p["B"][0], "by": p["B"][1]},
            "white": {"x": D65[0], "y": D65[1]}, "white_source": "d65", "target_luminance": 1000.0,
            "channel_peak_xyz": [list(v) for v in ramps()[2]], "dark_floor": {"nits": 0.1},
            "peak_chroma": {"wrgb_nonadditive": False}, "level_edge": block}


def _hdr_calib(tmp_path, name, block, *, switch="auto", adjudicator=None):
    from test_calibrate import _make, _perfect_hdr_panel
    calib = _make(tmp_path, name, mode="HDR", panel=_perfect_hdr_panel(), bit_depth=10, adjudicator=adjudicator)
    calib.profile.targets["rec2020_pq"] = replace(calib.profile.targets["rec2020_pq"], level_edge=switch)
    calib.stage_resolve_target()
    calib._state["mhc_params"] = _mhc_params(block)
    calib.calib["oog_mapping"] = "vertex"
    calib._save()
    return calib


def test_build_decides_pins_and_reports_the_level_edge(tmp_path, law_block):
    calib = _hdr_calib(tmp_path, "le_on", law_block)
    assert calib._white_xy() == pytest.approx(D65)
    cfg = replace(calib._cube_optimize_config(), oog_solve="projection")
    drives = _mixed_drives()
    reach, block = calib._cube_level_edge(cfg, calib._engine_target(), drives, law_xyz(drives))
    assert hasattr(reach, "full_primaries") and reach.key() == law_block["key"]
    memo = calib.calib["oog_level_edge"]
    assert memo["enabled"] is True and memo["key"] == law_block["key"] and memo["falsification"]["passed"] is True
    assert block["enabled"] is True and block["lattice"]["newly_clamped"] >= 0
    assert block["verify_plan"]["patches"] > 0 and block["verify_plan"]["targets_moved"] >= 0
    assert calib._reachable_gamut(stage="verify").key() == law_block["key"]
    # the same build with the switch off: full-drive triangle, memo pinned off, build digest untouched
    off = _hdr_calib(tmp_path, "le_off", law_block, switch="off")
    reach2, block2 = off._cube_level_edge(cfg, off._engine_target(), drives, law_xyz(drives))
    assert isinstance(reach2, dict) and block2 is None
    assert off.calib["oog_level_edge"]["enabled"] is False and "profile" in off.calib["oog_level_edge"]["reason"]


def test_a_falsified_edge_goes_to_the_llm_and_is_disabled_by_default(tmp_path, law_block):
    from test_calibrate import _RecordingAuto
    adj = _RecordingAuto()
    calib = _hdr_calib(tmp_path, "le_fals", law_block, adjudicator=adj)
    cfg = replace(calib._cube_optimize_config(), oog_solve="projection")
    drives = _mixed_drives()
    reach, block = calib._cube_level_edge(cfg, calib._engine_target(), drives, law_xyz(drives, c=0.0))
    seams = [r for r in adj.requests if r.key == "build-install-3dlut:level_edge_falsified"]
    assert len(seams) == 1 and seams[0].options == ("disable", "enable", "abort")
    assert seams[0].recommendation == "disable" and seams[0].digest["falsification"]["passed"] is False
    json.dumps(seams[0].digest)
    assert isinstance(reach, dict) and block["enabled"] is False
    assert calib.calib["oog_level_edge"]["enabled"] is False
    assert "falsified" in calib.calib["oog_level_edge"]["reason"]


def test_a_key_mismatch_after_the_build_goes_to_the_llm(tmp_path, law_block):
    from test_calibrate import _RecordingAuto
    adj = _RecordingAuto()
    calib = _hdr_calib(tmp_path, "le_mismatch", law_block, adjudicator=adj)
    calib.calib["oog_level_edge"] = {"enabled": True, "key": "sha256:built-for-this", "reason": None,
                                     "falsification": None}
    reach = calib._reachable_gamut(stage="verify")
    seams = [r for r in adj.requests if r.key == "verify:level_edge_key_mismatch"]
    assert len(seams) == 1 and seams[0].options == ("use_current", "disable", "abort")
    assert seams[0].recommendation == "disable"
    assert isinstance(reach, dict) and calib.calib["oog_level_edge"]["enabled"] is False


def test_stage_cli_score_equals_the_live_verify_score_for_a_level_edge_run(tmp_path, law_block):
    from dlc.stages import score as score_stage
    calib = _hdr_calib(tmp_path, "le_verify", law_block)
    calib.calib["oog_level_edge"] = {"enabled": True, "key": law_block["key"], "reason": None,
                                     "falsification": {"passed": True}}
    calib._save()
    rng = np.random.default_rng(9)
    sig = np.vstack([_mixed_drives(20), np.repeat(np.linspace(0.1, 0.75, 10)[:, None], 3, 1),
                     rng.uniform(0.05, 0.6, (40, 3))])
    meas = RAW.ideal_xyz(sig) * (1 + 0.01 * rng.standard_normal(sig.shape))
    ti3 = _write_ti3(calib.ctx.root / "measurements" / "verify.ti3", sig, np.maximum(meas, 0.0))
    live = calib.stage_verify(str(ti3)).digest
    assert live["gamut_aware"] is True
    for key in ("full_drive_target", "reclassified", "level_edge_falsification", "verdict_depends_on_level_edge"):
        assert key in live, key
    assert set(live["full_drive_target"]) == {"core", "limits", "clamped", "tube", "all"}
    args = Namespace(stage="verify", iteration=1, source_ti3=str(ti3), gamma=2.2, luminance=None,
                     target_white_xy=None, level_edge="run", mode="HDR", run=calib.ctx.root)
    res = score_stage.build(args, calib.ctx)
    assert res.metrics["practical"] == live["practical"]
    assert res.metrics["level_edge"]["key"] == law_block["key"]
    off = score_stage.build(Namespace(**{**vars(args), "level_edge": "off"}), calib.ctx)
    assert off.metrics["practical"]["clamped"] == live["full_drive_target"]["clamped"]


def test_level_edge_cli_computes_and_writes_the_block_without_touching_the_scoring_memo(tmp_path):
    from dlc.runs import create_run
    from dlc.stages import _common
    from dlc.stages import level_edge as le_stage
    ctx = create_run("HDR", display="synthetic", run_dir=tmp_path / "le_cli")
    rgb, xyz, peaks = ramps()
    _write_ti3(ctx.root / "measurements" / "raw.ti3", rgb, xyz)
    mp = _mhc_params({"full_primaries": fit()["full_primaries"]})
    mp.pop("level_edge")
    _common.save_dlc_state(ctx, {"mhc_params": mp, "calib": {"stages": {"verify": {"status": "done"}}}})
    args = Namespace(source_ti3=None, write=False, mode="HDR", run=ctx.root)
    res = le_stage.build(args, ctx)
    assert res.metrics["level_edge"]["status"] == "ok" and res.metrics["falsification"]["raw"]["passed"] is True
    missing = le_stage.build(Namespace(**{**vars(args), "source_ti3": "no_such.ti3"}), ctx)
    assert missing.status == "failed"                                # an explicit source is never substituted
    assert "level_edge" not in _common.load_dlc_state(ctx)["mhc_params"]
    le_stage.build(Namespace(**{**vars(args), "write": True}), ctx)
    state = _common.load_dlc_state(ctx)
    assert state["mhc_params"]["level_edge"]["status"] == "ok"
    assert "oog_level_edge" not in state["calib"]                     # a legacy run keeps scoring as it did
    assert M.run_level_edge(state["calib"], state["mhc_params"], switch="auto", oog_solve="projection")[0] is None


def test_an_hdr_mhc_build_persists_the_level_edge_and_reports_it(tmp_path):
    from test_calibrate import _make, _perfect_hdr_panel
    calib = _make(tmp_path, "le_mhc", mode="HDR", panel=_perfect_hdr_panel(), bit_depth=10)
    assert calib.run("mhc-only").status == "completed"
    block = calib._state["mhc_params"]["level_edge"]
    assert block["schema"] == LG.SCHEMA and block["status"] in ("ok", "rejected", "unavailable")
    digest = calib.calib["stages"]["build-install-mhc"]["digest"]["level_edge"]
    assert digest["status"] == block["status"] and digest["key"] == block.get("key")
    assert "oog_level_edge" not in calib.calib                       # nothing decided before a 3D-LUT build
