"""Render a self-contained HTML run report — a permanent artifact the Export button writes.

It embeds the run state + chart data and inlines the shared chart renderer (``charts.js``),
so the file opens later with no server and reproduces the dashboard's charts. The summary
numbers are server-rendered as static HTML, so they're legible even with scripting off.
Stdlib-only (html + json), like the rest of the dashboard.
"""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any, Optional


def _num(v: Any, d: int = 2) -> str:
    try:
        return f"{float(v):.{d}f}"
    except (TypeError, ValueError):
        return "—"


def _row(label: str, value: Any) -> str:
    return f"<tr><th>{html.escape(label)}</th><td>{html.escape('' if value is None else str(value))}</td></tr>"


def _de_table(de: dict[str, Any]) -> str:
    if not de:
        return "<p class='muted'>No scored ΔE yet (verify has not run).</p>"
    cells = [("avg", de.get("avg")), ("95th", de.get("p95")), ("99th", de.get("p99")),
             ("max", de.get("max")), ("white", de.get("white")),
             ("grayscale", de.get("grayscale")), ("colour", de.get("colour"))]
    tds = "".join(f"<div class='bn'><b>{_num(v)}</b><label>{html.escape(k)}</label></div>" for k, v in cells)
    src = de.get("phase") or ""
    return f"<div class='bignums'>{tds}</div><p class='muted'>source: {html.escape(str(src))}</p>"


def _safe_json(obj: Any) -> str:
    # Embed in a <script> without letting a literal </script> or HTML comment break out.
    return (json.dumps(obj, separators=(",", ":"))
            .replace("</", "<\\/").replace("<!--", "<\\!--"))


def render_report_html(snap: dict[str, Any], charts: dict[str, Any], exported_at: str,
                       assets_dir: Path) -> str:
    """Build the standalone report HTML for one point-in-time snapshot."""
    h = snap.get("header") or {}
    white = h.get("white") or {}
    counters = snap.get("counters") or {}
    timers = snap.get("timers") or {}
    run_id = h.get("run_id") or snap.get("run_id") or "run"

    summary = "".join([
        _row("run", run_id),
        _row("display", h.get("display")),
        _row("monitor", h.get("monitor")),
        _row("mode", h.get("mode")),
        _row("flow", h.get("flow")),
        _row("bit depth", h.get("bit_depth")),
        _row("target", h.get("target")),
        _row("gamma", h.get("gamma")),
        _row("white", (f"{_num(white.get('cct'),0)} K  ({_num((white.get('xy') or [None,None])[0],4)}, "
                       f"{_num((white.get('xy') or [None,None])[1],4)})" if white else None)),
        _row("ccmx", h.get("ccmx")),
        _row("spd", h.get("spd")),
        _row("status", snap.get("run_status")),
        _row("patches", f"{counters.get('patches_done', 0)} / {counters.get('patches_total', 0)}"),
        _row("reads (ok/fail)", f"{counters.get('reads_ok', 0)} / {counters.get('reads_failed', 0)}"),
        _row("run elapsed", _num(timers.get("run_elapsed_s"), 0) + " s" if timers.get("run_elapsed_s") is not None else None),
        _row("exported", exported_at),
    ])

    try:
        charts_js = (assets_dir / "charts.js").read_text(encoding="utf-8")
    except OSError:
        charts_js = ""

    chart_cards = "".join(
        f'<figure class="chart"><figcaption>{html.escape(title)}</figcaption>'
        f'<div data-chart="{key}"></div></figure>'
        for key, title in (("cie", "CIE 1931 chromaticity"), ("eotf", "EOTF / gamma"),
                           ("graycct", "Grayscale CCT"), ("grayduv", "Grayscale Duv"),
                           ("optimizer", "Optimizer convergence"), ("drift", "White CCT vs time")))

    payload = _safe_json({"charts": charts, "header": h})

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"/>
<title>DLC report · {html.escape(str(run_id))}</title>
<style>{_REPORT_CSS}</style></head>
<body>
<h1>DLC calibration report</h1>
<div class="cols">
  <section class="card"><h2>Summary</h2><table class="kv">{summary}</table></section>
  <section class="card"><h2>ΔE2000</h2>{_de_table(snap.get('de') or {})}</section>
</div>
<section class="card"><h2>Charts</h2><div class="charts" id="charts">{chart_cards}</div></section>
<p class="muted">Generated by the DLC mission-control dashboard — self-contained (no server needed).</p>
<script id="report-data" type="application/json">{payload}</script>
<script>{charts_js}</script>
<script>
(function(){{
  try {{
    var D = JSON.parse(document.getElementById("report-data").textContent);
    if (window.DLCCharts) window.DLCCharts.renderInto(document.getElementById("charts"), D.charts, D.header);
  }} catch (e) {{ console.error("report render failed", e); }}
}})();
</script>
</body></html>"""


_REPORT_CSS = """
:root{--bg:#0d1117;--panel:#161b22;--edge:#2a313c;--ink:#e6edf3;--dim:#8b949e;--accent:#58a6ff;
--good:#3fb950;--mono:ui-monospace,Consolas,monospace}
*{box-sizing:border-box}body{background:var(--bg);color:var(--ink);font-family:Segoe UI,system-ui,sans-serif;
margin:0;padding:20px;font-size:13px}h1{font-size:18px;margin:0 0 14px}h2{font-size:12px;text-transform:uppercase;
letter-spacing:1px;color:var(--dim);margin:0 0 10px}.cols{display:flex;gap:14px;flex-wrap:wrap;margin-bottom:14px}
.card{background:var(--panel);border:1px solid var(--edge);border-radius:8px;padding:14px;flex:1 1 320px}
table.kv{width:100%;border-collapse:collapse}table.kv th{text-align:left;color:var(--dim);font-weight:400;
padding:2px 8px 2px 0;white-space:nowrap}table.kv td{font-family:var(--mono);padding:2px 0}
.bignums{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.bn{background:#1c2330;border-radius:6px;
padding:8px;text-align:center}.bn b{display:block;font-family:var(--mono);font-size:17px;color:var(--good)}
.bn label{color:var(--dim);font-size:10px;text-transform:uppercase}.muted{color:#5b636d;font-size:11px}
.charts{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:14px}
.chart{background:#0f141b;border:1px solid var(--edge);border-radius:8px;padding:8px;margin:0}
.chart figcaption{color:var(--dim);font-size:11px;text-transform:uppercase;letter-spacing:.5px;margin-bottom:6px}
.chart-svg{width:100%;height:auto;display:block}
.ch-area{fill:#0a0e13;stroke:#1f2733}.ch-grid{stroke:#1a212b;stroke-width:.5}.ch-tick{fill:#5b636d;font-size:9px;font-family:var(--mono)}
.ch-locus{stroke:#6e7681;stroke-width:1;stroke-dasharray:3 2}.ch-gamut{fill:none;stroke:#3a4452;stroke-width:1}
.ch-pt{fill:#d2693a;opacity:.55}.ch-pt-n{fill:#58a6ff;opacity:.8}.ch-white{fill:#fff;stroke:#000;stroke-width:.5}
.ch-line{stroke:#58a6ff;stroke-width:1.5}.ch-line-max{stroke:#f85149;stroke-width:1}.ch-ref{stroke:#3fb950;stroke-width:1;stroke-dasharray:4 3}
.ch-dot{fill:#58a6ff}.ch-dot-max{fill:#f85149}.ch-note{fill:#8b949e;font-size:10px;font-family:var(--mono)}
.ch-empty{fill:#5b636d;font-size:12px;font-family:var(--mono)}
"""
